server:
  port: 8081

spring:
  application:
    name: calculation-service

  datasource:
    url: jdbc:mysql://localhost:3306/calculation_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
